# Generated by Django 3.2.5 on 2021-11-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pds_inlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pds_inlet', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pds_outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pds_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('pds_inlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.pds_inlet')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod', models.CharField(blank=True, max_length=200, null=True)),
                ('rack_number', models.CharField(blank=True, max_length=200, null=True)),
                ('rack_type', models.CharField(blank=True, max_length=200, null=True)),
                ('supply_type', models.CharField(blank=True, max_length=200, null=True)),
                ('rpdu_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swbd_outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swbd_outlet', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Swgr_inlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swgt_inlet', models.CharField(blank=True, max_length=200, null=True)),
                ('pds_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.pds_outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Ups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ups_number', models.CharField(blank=True, max_length=200, null=True)),
                ('swbd_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.swbd_outlet')),
            ],
        ),
        migrations.CreateModel(
            name='Udp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udp_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.ups')),
            ],
        ),
        migrations.CreateModel(
            name='Swgr_outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swgr_outlet', models.CharField(blank=True, max_length=200, null=True)),
                ('swgr_inlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.swgr_inlet')),
            ],
        ),
        migrations.AddField(
            model_name='swbd_outlet',
            name='swgr_outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.swgr_outlet'),
        ),
        migrations.CreateModel(
            name='Rpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpp_number', models.CharField(blank=True, max_length=200, null=True)),
                ('udp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.udp')),
            ],
        ),
        migrations.CreateModel(
            name='Rack_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_number', models.CharField(blank=True, max_length=200, null=True)),
                ('plug_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ats_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ats_sn', models.CharField(blank=True, max_length=200, null=True)),
                ('rpdu_number', models.CharField(blank=True, max_length=200, null=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.rack')),
                ('rpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.rpp')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.site')),
            ],
        ),
        migrations.AddField(
            model_name='pds_inlet',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwcd_eam.site'),
        ),
    ]
