# Generated by Django 3.2.5 on 2021-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcd_eam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='ccu_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
