# Generated by Django 3.2.5 on 2021-11-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcd_eam', '0002_rack_ccu_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_DateTime', models.CharField(blank=True, max_length=225, null=True)),
                ('configuration_Item_Name', models.CharField(blank=True, max_length=225, null=True)),
                ('configuration_Item_Description', models.CharField(blank=True, max_length=225, null=True)),
                ('configuration_Item_Value', models.CharField(blank=True, max_length=225, null=True)),
                ('previouse_item_value', models.CharField(blank=True, max_length=225, null=True)),
                ('modificaiton_Methods', models.CharField(blank=True, max_length=225, null=True)),
                ('configuration_Item_Value_Range', models.CharField(blank=True, max_length=225, null=True)),
                ('configuration_Item_Value_Type', models.CharField(blank=True, max_length=225, null=True)),
                ('condition_For_Validity', models.CharField(blank=True, max_length=225, null=True)),
                ('configuration_Item_Level', models.CharField(blank=True, max_length=225, null=True)),
                ('software_Name', models.CharField(blank=True, max_length=225, null=True)),
                ('device_Name', models.CharField(blank=True, max_length=225, null=True)),
                ('device_Description', models.CharField(blank=True, max_length=225, null=True)),
                ('subsystem', models.CharField(blank=True, max_length=225, null=True)),
                ('system', models.CharField(blank=True, max_length=225, null=True)),
                ('facility', models.CharField(blank=True, max_length=225, null=True)),
                ('site', models.CharField(blank=True, max_length=225, null=True)),
                ('come_From', models.CharField(blank=True, max_length=225, null=True)),
                ('more_Remark', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
