# Generated by Django 3.2.5 on 2021-11-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcd_eam', '0003_equipment_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment_config',
            name='come_From',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项内容来源'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='condition_For_Validity',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项值有效条件'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='configuration_Item_Description',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项名称描述'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='configuration_Item_Level',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项级别'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='configuration_Item_Name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项名称'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='configuration_Item_Value',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项当前值'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='configuration_Item_Value_Range',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项值设置范围'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='configuration_Item_Value_Type',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项值类型'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='device_Description',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项硬件设备名称描述'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='device_Name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项硬件设备名称'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='facility',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项基础设施类型'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='modificaiton_Methods',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项变更方式'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='more_Remark',
            field=models.TextField(blank=True, null=True, verbose_name='配置项更多备注'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='previouse_item_value',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项前值'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='site',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项站点'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='software_Name',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项软件名称和版本'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='subsystem',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项子系统'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='system',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='配置项系统'),
        ),
        migrations.AlterField(
            model_name='equipment_config',
            name='update_DateTime',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='更新时间'),
        ),
    ]
