# Generated by Django 3.2.5 on 2021-11-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcd_eam', '0004_auto_20211118_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack_config',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='rack_config',
            name='rpp',
        ),
        migrations.AddField(
            model_name='rack_config',
            name='ccu_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='pds_inlet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='pds_outlet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='pod_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='rack_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='rack_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='rpdu_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='rpp_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='supply_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='swbd_outlet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='swgr_inlet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='swgr_outlet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='udp_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rack_config',
            name='ups_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rack_config',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
